language: generic
sudo: required
services:
  - docker
script:
  - docker build -t breakingpitt/terraform-alpine alpine
  - docker build -t breakingpitt/terraform-ubuntu ubuntu
git:
  depth: 3
  submodules: false
branches:
  only:
    - master

